baseURL = 'https://jonahgiuliano.github.io/jonahandlydia/'
canonifyURLs = true

languageCode = 'en-us'
title = 'Lydia Martin and Jonah Giuliano'
subtitle = 'Lydia Martin and Jonah Giuliano'
theme = 'huey'

useIndexContent = true
